labeledRoles:
  - Admin
  - Reasonable
  - Moderate
  - Unreasonable
roles: 
  - League
  - Minecraft
protectedRoles:
  - "@everyone"
  - Viceroy
channelTypes: 
  - Voice
  - Text
channels: 
  - General: 
      permissions: 
        Admin: all
        Reasonable: general
        Moderate: general
        Unreasonable: general
      type: Voice
  - general: 
      permissions: 
        Admin: all
        Reasonable: general
        Moderate: general
        Unreasonable: general
      type: Text
  - league: 
      permissions: 
        Admin: all
        League: general
      type: Text
  - Minecraft:
      permissions: 
        Admin: all
        Minecraft: general
      type: Voice
  - minecraft:
      permissions: 
        Admin: all
        Minecraft: general
      type: Text